build:
  ci:
    - echo "true"

jobs:
  - name: job-A
    type: runSh
    steps:  
      - TASK:
        - script: secs=30; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        - script: shipctl post_resource_state state-1 "MESSAGE" "build_"$BUILD_NUMBER
        - script: shipctl post_resource_state state-2 "MESSAGE" "build_"$BUILD_NUMBER        
      - OUT: state-1
      - OUT: state-2

  - name: chrono
    type: runSh
    dependencyMode: chrono
    steps:
      - IN: state-1
      - IN: state-2      
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: immediate
    type: runSh
    dependencyMode: immediate
    steps:
      - IN: state-1
      - IN: state-2      
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: strict 
    type: runSh
    dependencyMode: strict
    steps:
      - IN: state-1
      - IN: state-2   
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         



resources:
  - name: state-1
    type: state
    
  - name: state-2
    type: state    
