jobs:
  - name: file-manifest
    type: manifest
    steps:
      - IN: file-resource
      - IN: params

  - name: deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster
      - TASK:
        - script: sudo mkdir -p /home/shippable/Documents

resources:
  - name: file-resource
    type: file
    pointer:
      sourceName: https://raw.githubusercontent.com/ankul-shippable/sample_node/master/shippable.yml
    seed:
      versionName: initial
      
  - name: cluster
    type: cluster
    integration: "nodes-list"
    
  - name: params
    type: params
    version:
      params:
        KEY1: "value1"
        KEY2: "value2"      
