build:
  ci:
    - echo "true"

jobs:
  - name: job-1
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: job-2
    type: runSh
    steps:
      - IN: job-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-3
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: job-4
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

  - name: job-in-1
    type: runSh
    steps:
      - IN: job-2
      - IN: job-3 
      - IN: state-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-in-2
    type: runSh
    steps:
      - IN: job-4
      - IN: state-2     
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

  - name: job-in-out
    type: runSh
    steps:
      - IN: state-1
      - IN: state-2
      - IN: job-in-1
      - IN: job-in-2      
      - TASK:
        - script: shipctl get_resource_version_key state-1 "MESSAGE"
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state state-1 "MESSAGE" "build_"$BUILD_NUMBER
        - script: shipctl post_resource_state state-2 "MESSAGE" "build_"$BUILD_NUMBER
      - OUT: state-1
      - OUT: state-2

  - name: state-job-out
    type: runSh
    steps:
      - IN: state-1
      - IN: state-2      
      - IN: job-in-out
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: b_job-1
    type: runSh
    steps:  
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: b_job-2
    type: runSh
    steps:
      - IN: b_job-1
      - IN: b_state-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

  - name: b_job-2
    type: runSh
    steps:
      - IN: b_state-1
      - IN: b_job-2     
      - TASK:
        - script: shipctl get_resource_version_key b_state-1 "MESSAGE"
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state b_state-1 "MESSAGE" "build_"$BUILD_NUMBER
      - OUT: b_state-1

resources:
  - name: state-1
    type: state
    
  - name: state-2
    type: state
    
  - name: b_state-1
    type: state    
