jobs:
  - name: gcloud
    type: runSh
    steps:
      #- IN: time-1
      - TASK:
        - script: echo "gcloud"
        
  - name: aws
    type: runSh
    steps:
      - IN: time-2
      - TASK:   
        - script: echo "aws"
resources:

  - name: time-1
    type: time
    seed:
       interval: "*/10 * * * *"
       
  - name: time-2
    type: time
    seed:
       interval: "*/20 * * * *"
       
  - name: time-3
    type: time
    seed:
       interval: "*/30 * * * *"       
       
  - name: time-4
    type: time
    #seed:
       #interval: "*/40 * * * *"#
