build:
  ci:
    - echo "true"

jobs:
  - name: job-1
    type: runSh
    steps:  
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: job-2
    type: runSh
    steps:
      - IN: job-1
      - IN: state-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

  - name: job-3
    type: runSh
    steps:
      - IN: state-1
      - IN: job-2     
      - TASK:
        - script: shipctl get_resource_version_key state-1 "MESSAGE"
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state state-1 "MESSAGE" "build_"$BUILD_NUMBER
      - OUT: state-1

  - name: c-job-1
    type: runSh
    steps:  
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: c-job-2
    type: runSh
    steps:
      - IN: c-job-1
      - OUT: c-state-1
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state c-state-1 "MESSAGE" "build_"$BUILD_NUMBER

  - name: c-job-3
    type: runSh
    steps:
      - IN: c-job-2     
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done


resources:
  - name: state-1
    type: state
    
  - name: c-state-1
    type: state    
