jobs:
  - name: gcloud
    type: runSh
    steps:
      - IN: gcloud-cli
      - TASK:
        - script: gcloud container clusters list
        
  - name: aws
    type: runSh
    steps:
      - IN: aws-cli
      - TASK:
        - script: aws ec2 describe-instances        

resources:
  - name: gcloud-cli
    type: cliConfig
    integration: "gke-subint"
    pointer:
      region: "us-central1-a"
      clusterName: "gke-cluster-2"
      
  - name: aws-cli
    type: cliConfig
    integration: "aws-subint"
    pointer:
      region: "us-west-2"
