jobs:
  - name: gcloud
    type: runSh
    steps:
      - IN: gcloud-cli
      - TASK: DCL-cluster
        - script: gcloud container clusters list

resources:
  - name: gcloud-cli
    type: cliConfig
    integration: "gcp-subint"
    pointer:
      region: "dcl-cluster"
      clusterName: "gke-cluster"
