build:
  ci:
    - echo "true"

jobs:
  - name: state-job-in
    type: runSh
    steps:
      - IN: state-resource
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: job-with-state
    type: runSh
    steps:
      - IN: state-resource
      - IN: state-job-in
      - TASK:
        - script: shipctl get_resource_version_key state-resource "MESSAGE"
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state state-resource "MESSAGE" "build_"$BUILD_NUMBER
      - OUT: state-resource

  - name: state-job-out
    type: runSh
    steps:
      - IN: state-resource
      - IN: job-with-state
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: state-job-in-2
    type: runSh
    steps:
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done

  - name: job-with-state-2
    type: runSh
    steps:
      - IN: state-resource-2
      - IN: state-job-in-2
      - TASK:
        - script: shipctl get_resource_version_key state-resource-2 "MESSAGE"
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state state-resource-2 "MESSAGE" "build_"$BUILD_NUMBER
      - OUT: state-resource-2

  - name: state-job-out-2
    type: runSh
    steps:
      - IN: job-with-state-2
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: c-job-1
    type: runSh
    steps:
      - IN: c-res-1
      - OUT: c-res-2      
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done    
        
  - name: d-job-1
    type: runSh
    steps:
      - IN: d-res-1
      - OUT: d-res-1      
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done            

resources:
  - name: state-resource
    type: state
    
  - name: state-resource-2
    type: state    

  - name: c-res-1
    type: state  

  - name: c-res-2
    type: state  
    
  - name: c-res-1
    type: state      
