jobs:
  - name: file-manifest
    type: manifest
    steps:
      - IN: file-resource

  - name: deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster

resources:
  - name: file-resource
    type: file
    pointer:
      sourceName: https://raw.githubusercontent.com/ankul-shippable/sample_node/master/shippable.yml
    seed:
      versionName: initial
      
  - name: cluster
    type: cluster
    integration: "nodes-list"
