jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image
      
  - name: DCL-deploy
    type: deploy
    steps:
      - IN: manifest-job
      - IN: DCL-cluster       

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: DCL-cluster
    type: cluster
    integration: "dcl-subint"
    pointer:
      sourceName: "dcl-cluster"      
