jobs:
  - name: manifest_job
    type: manifest
    steps:
      - IN: nginx_image
      
  - name: DCL-deploy
    type: deploy
    steps:
      - IN: manifest_job
      - IN: DCL-cluster       

resources:
  - name: nginx_image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: DCL-cluster
    type: cluster
    integration: "dcl-subint"
    pointer:
      sourceName: "dcl-cluster"      
