build:
  ci:
    - echo "true"

jobs:
  - name: job-1
    type: runSh
    steps:
      - OUT: nginx_1 
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: failing it

  - name: job-2
    type: runSh
    steps:
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: job-3
    type: runSh
    steps:
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
    
  - name: job-4
    type: runSh
    steps:
      - OUT: resource-1
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        - script: shipctl post_resource_state resource-1 versionName job-4_$BUILD_NUMBER
        
  - name: job-5
    type: runSh
    steps:
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done
        
  - name: job-6
    type: runSh
    steps:
      - TASK:
        - script: secs=60; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done    
        
  - name: strict-job-1
    type: runSh
    steps:
      - IN: job-1
      - IN: resource-1
      - IN: resource-2
      - IN: job-2
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done      
        
  - name: strict-job-2
    type: runSh
    steps:
      - IN: resource-1
      - IN: resource-2
      - IN: job-2
      - IN: job-3
      - TASK:
        - script: secs=1; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done              

resources:
  - name: resource-1
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: resource-2
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11
