resources:
  - name: timer
    type: time
    seed:
       interval: "*/10 * * * *"
       
  - name: timer-2
    type: time
    seed:
       interval: "*/10 * * * *"       
       
jobs:
  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: timer
      
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: timer
      
  - name: sample_c_runCI
    type: runCI
    steps:
      - IN: timer
      
  - name: coverage_sample_runCI
    type: runCI
    steps:
      - IN: timer
      
  - name: sample_python_runCI
    type: runCI
    steps:
      - IN: timer

  - name: pipelines_runCI
    type: runCI
    steps:
      - IN: timer
