jobs:
  - name: file-manifest
    type: manifest
    steps:
      - IN: file-resource
      - IN: params

  - name: deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster
      - TASK:
        - script: sudo mkdir -p /home/shippable/Documents

  - name: bastian-deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster-2
      - IN: bastian-access
      - TASK:
        - script: sudo mkdir -p /home/random/documents
        
  - name: bastian-printenv
    type: runSh
    steps:
      - IN: bastian-access
      - TASK:
        - script: printenv
        - script: sudo ls /build/IN/bastian-access/


resources:
  - name: file-resource
    type: file
    pointer:
      sourceName: https://raw.githubusercontent.com/ankul-shippable/sample_node/master/shippable.yml
    seed:
      versionName: initial
      
  - name: cluster
    type: cluster
    integration: "nodes-list"

  - name: bastian-access
    type: integration
    integration: "bastian-host-access"

  - name: cluster-2
    type: cluster
    integration: "nodes-list-2"
    pointer:
      bastionHost:
        address: 35.188.86.124
        user: ubuntu
        keyIntegration: bastian-access
        nodeUser: random
    
  - name: params
    type: params
    version:
      params:
        KEY1: "value1"
        KEY2: "value2"      
