jobs:
  - name: file-manifest
    type: manifest
    steps:
      - IN: file-resource
      - IN: params

  - name: deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster
      - IN: sample_java-repo
      - TASK:
        - script: sudo mkdir -p /home/ankul/documents

  - name: bastian-deploy
    type: deploy
    steps:
      - IN: file-manifest
      - IN: cluster-2
      - IN: bastian-access
      - IN: sample_java-repo
      - TASK:
        - script: sudo mkdir -p /home/ankul/documents
        
  - name: bastian-printenv
    type: runSh
    steps:
      - IN: bastian-access
      - TASK:
        #- script: printenv
        - script: sudo cat $BASTIANACCESS_PRIVATE_KEY_PATH


resources:
  - name: file-resource
    type: file
    pointer:
      sourceName: https://raw.githubusercontent.com/ankul-shippable/sample_node/master/shippable.yml
    seed:
      versionName: initial
      
  - name: cluster
    type: cluster
    integration: "nodes-list"

  - name: bastian-access
    type: integration
    integration: "bastian-host-access"

  - name: cluster-2
    type: cluster
    integration: "nodes-list-2"
    versionTemplate:
      bastionHost:
        address: 35.224.151.61
        user: ankul
        keyIntegration: bastian-access
    
  - name: params
    type: params
    version:
      params:
        KEY1: "value1"
        KEY2: "value2"      

  - name: sample_java-repo
    type: gitRepo
    integration: "github-subint"
    pointer:
      sourceName: ankul-shippable/sample_java
      branch: master
