jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image
      
  - name: DCL-deploy
    type: deploy
    method: upgrade
    steps:
      - IN: manifest-job
      - IN: DCL-cluster
      - IN: scaler
      
  - name: DDC-deploy
    type: deploy
    #method: upgrade
    steps:
      - IN: manifest-job
      - IN: DDC-cluster
      - IN: scaler      

resources:
  - name: scaler
    type: replicas
    version:
      count: 1

  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
      
  - name: DCL-cluster
    type: cluster
    integration: "dcl-subint"
    pointer:
      sourceName: "dcl-cluster"
      
  - name: DDC-cluster
    type: cluster
    integration: "ddc-subint"      
