build:
  ci:
    - echo "true"

jobs:
  - name: job-A
    type: runSh
    steps:  
      - TASK:
        - script: secs=30; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        - script: shipctl post_resource_state img-1 versionName "build_"$BUILD_NUMBER
        - script: shipctl post_resource_state img-2 versionName "build_"$BUILD_NUMBER        
      - OUT: img-1
      - OUT: img-2

  - name: job-B
    type: runSh
    steps:
      - TASK:
        - script: secs=120; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: chrono
    type: runSh
    dependencyMode: chrono
    steps:
      - IN: img-1
      - IN: img-2
      - IN: job-B
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 

  - name: immediate
    type: runSh
    dependencyMode: immediate
    steps:
      - IN: job-A
      - IN: job-B      
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done 
        
  - name: strict 
    type: runSh
    dependencyMode: strict
    steps:
      - IN: img-1
      - IN: img-2
      - IN: job-B      
      - TASK:
        - script: secs=10; SECONDS=0; while (( SECONDS < secs )); do sleep 1; echo $SECONDS; done         

resources:
  - name: img-1
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.10
    
  - name: img-2
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/nginx"
    seed:
      versionName: prod.11
